---
title: "p8105_hw3_ts3349"
author: "Tessa Senders"
date: "10/6/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(p8105.datasets)
```

## Problem 1


```{r load data prob 1}
data("instacart")
```
This dataset contains `r nrow(instacart)` rows and `r ncol(instacart)` columns.  Observations are the level of items in orders by user.  There are user/order variables-user ID, order ID, order day, and order hour.  There are also item variables-name, aisle, department, and some numeric codes.



How many aisles and which are most items from?

```{r prob 1 counting}
instacart %>%
  count(aisle) %>%
  arrange(desc(n))
```

Plot

```{r prob 1 plot}
instacart %>%
  count(aisle) %>%
  filter(n > 10000) %>%
  mutate(
    aisle = factor(aisle),
    aisle = fct_reorder(aisle, n)
  ) %>%
  ggplot(aes(x = aisle, y = n)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 1))
```

Table

```{r prob 1 table}
instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>%
  count(product_name) %>%
  mutate(rank = min_rank(desc(n))) %>%
  filter(rank < 4) %>%
  arrange(aisle, rank) %>%
  knitr::kable()

```

Second Table

```{r prob 1 table 2}
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour
  ) %>%
  knitr::kable()

```

